{'../ejabberd-dev/src/gen_mod', [{outdir, "../ejabberd-dev/ebin"},{i,"../ejabberd-dev/include"}]}.
{'src/mod_offline_post', [{outdir, "ebin"},{i,"../ejabberd-dev/include/"},{pa,"../ejabberd-dev/ebin/"}]}.

